export const AUTH_SIGN_UP_SUCESS = "AUTH_SIGN_UP_SUCESS";
export const AUTH_SIGN_UP_START = "AUTH_SIGN_UP_START";
export const AUTH_SIGN_UP_FAIL = "AUTH_SIGN_UP_FAIL";

export const LOGOUT_USER = "LOGOUT_USER";

export const AUTH_SIGN_UP_MAIN_SUCESS = "AUTH_SIGN_UP_MAIN_SUCESS";
export const AUTH_SIGN_UP_MAIN_FAIL = "AUTH_SIGN_UP_MAIN_FAIL";

export const USER_ERROR_DISPLAY = " USER_ERROR_DISPLAY";

export const REMOVE_ALL_ERROR = "REMOVE_ALL_ERROR";
